---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: unibee-admin-portal
  namespace: default
spec:
  selector:
    matchLabels:
      app: unibee-admin-portal
  replicas: 1
  template:
    metadata:
      labels:
        app: unibee-admin-portal
    spec:
      restartPolicy: Always
      containers:
        - name: unibee-admin-portal
          image: unibee/admin-portal:v1.5.2
          imagePullPolicy: IfNotPresent
          env:
            - name: UNIBEE_API_URL
              valueFrom:
                configMapKeyRef:
                  name: unibee-config
                  key: UNIBEE_API_URL
          ports:
            - containerPort: 80
              name: http

---
apiVersion: v1
kind: Service
metadata:
  name: unibee-admin-portal-svc
  namespace: default
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
  selector:
    app: unibee-admin-portal
